import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/lib/provider/provider";
import Sidebar from "@/components/ui/custom/Sidebar/Sidebar";
import { ThemeProvider } from "@/components/ui/custom/ThemeProvider";
import { WorkspaceProvider } from "@/components/WorkspaceProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ThemeProvider>
            <WorkspaceProvider>
              <main className="flex-1">{children}</main>
            </WorkspaceProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
